### ISSUE TITLE
Changing delay

### ISSUE THREAD

**Issue by asymmetric** [dapphub/ds-pause#11]
Changing the value of `delay` is not currently supported.

i assume this is a design decision based on the fact that it would be difficult to deal with the already scheduled proposals. If that's the case, maybe it's worth mentioning this in the README.

Have you considered allowing changes that strictly increase the delay? One benefit could be that, in cases when governance decides that all proposals in a `ds-pause` should be evaluated for longer, changing `delay` has less overhead than `cancel`ing each proposal and voting it back in on a different `ds-pause`.

**Comment by d-xo** [comment]
It is also possible to grief the system by maliciously increasing the delay to e.g. `MAX_UINT`.

Although since such a change must be delayed, I wonder if that's a problem at all. An attacker could just as well remove all the auth connections between e.g. `dss` and the `pause` to have the same effect.

**Comment by asymmetric** [comment]
How do you distinguish between griefing and a legitimate delay increase? Governance might legitimately decide to increase the delay to `MAX_UINT` for one or more `pause`s (at least temporarily), right?

**Comment by d-xo** [comment]
Once they set they delay to `MAX_UINT` they would have to wait `MAX_UINT` seconds to change it back.

**Comment by d-xo** [comment]
done in https://github.com/dapphub/ds-pause/pull/24
